# Remplace fadyl14 par ton vrai identifiant GitHub
image:
  repository: registry.gitlab.com/fadyl-axel-bamba-group/fadyl-axel-bamba-app
  tag: latest
  pullPolicy: Always

replicaCount: 2

service:
  type: ClusterIP
  port: 80
  targetPort: 5000

resources:
  requests:
    cpu: 50m
    memory: 64Mi
  limits:
    cpu: 200m
    memory: 128Mi

namespace: ns-fadyl-axel-bamba

etudiant:
  nom: "Fadyl Axel BAMBA"
  slug: "fadyl-axel-bamba"
